### PR TITLE
Issue #375: update to checkstyle 9.0.1

### LINKED ISSUE #374: upgrade to checkstyle 9.0
https://checkstyle.org/releasenotes.html#Release_9.0

### LINKED ISSUE #375: upgrade to checkstyle 9.0.1
https://checkstyle.org/releasenotes.html#Release_9.0.1

### PR DESCRIPTION
**Pull request by muhlba91**
fix #375 (closes #374 as well)

template + non-template checks working:
Screenshot 2021-10-30 at 4 11 12 PM

### CODE REVIEW

**Review by romani — APPROVED** [review]

**Comment by yokum3** [comment]
@romani , @muhlba91 : Did you also check if checkstyle 9.0.1 also compatible with latest SonarQube i.e 9.1 ?

**Comment by muhlba91** [comment]
I can confirm it's working on `9.0.1` as per my test configuration (https://github.com/checkstyle/sonar-checkstyle/blob/master/test-resources/docker-compose.yml#L8 <- M1 Mac).

**Comment by yokum3** [comment]
> I can confirm it's working on `9.0.1` as per my test configuration (https://github.com/checkstyle/sonar-checkstyle/blob/master/test-resources/docker-compose.yml#L8 <- M1 Mac).

Thanks for the quick update. I believe we have to also test on SonarQube 9.1 as you have tested it on 9.0.1. It seems below page is also broken Compatibility matrix from Sonar team: https://docs.sonarqube.org/display/PLUG/Plugin+Version+Matrix

**Comment by muhlba91** [comment]
@yokum3 plugin matrix is here: https://docs.sonarqube.org/latest/instance-administration/plugin-version-matrix/ and it lists 9.1 with 9.0.1 plugin.

**Pull request merged**
