### PR TITLE
Issue/302

### LINKED ISSUE #302: upgrade to checkstyle 8.35
https://checkstyle.org/releasenotes.html#Release_8.35

### PR DESCRIPTION
**Pull request by muhlba91**
fix #302 
based on #308 
do not merge before 4.34 is released and this branch rebased

### CODE REVIEW

**Comment by muhlba91** [comment]
@romani: i need some support to solve the build error.

```
java.lang.IllegalStateException: exception occured during getClass for com.puppycrawl.tools.checkstyle.checks.annotation.AnnotationUseStyleCheck$TrailingArrayComma
	at org.sonar.plugins.checkstyle.CheckstyleRulesDefinitionTest.test(CheckstyleRulesDefinitionTest.java:56)
Caused by: java.lang.ClassNotFoundException: com.puppycrawl.tools.checkstyle.checks.annotation.AnnotationUseStyleCheck$TrailingArrayComma
	at org.sonar.plugins.checkstyle.CheckstyleRulesDefinitionTest.test(CheckstyleRulesDefinitionTest.java:56)
```

```
java.lang.IllegalStateException: exception occured during getClass for com.puppycrawl.tools.checkstyle.checks.annotation.AnnotationUseStyleCheck$TrailingArrayComma
	at org.sonar.plugins.checkstyle.metadata.CheckstyleMetadataTest.getPreparedRepository(CheckstyleMetadataTest.java:48)
Caused by: java.lang.ClassNotFoundException: com.puppycrawl.tools.checkstyle.checks.annotation.AnnotationUseStyleCheck$TrailingArrayComma
	at org.sonar.plugins.checkstyle.metadata.CheckstyleMetadataTest.getPreparedRepository(CheckstyleMetadataTest.java:48)
```

hence, all come back to `ClassNotFoundException: com.puppycrawl.tools.checkstyle.checks.annotation.AnnotationUseStyleCheck$TrailingArrayComma`.

**Comment by romani** [comment]
@muhlba91 , please rebase on latest master after release of 8.34.

**Comment by romani** [comment]
@muhlba91 , 
please remove
https://github.com/checkstyle/sonar-checkstyle/blob/e971c6f961cef3e794beed369dd6bfe960ebdc11/src/main/java/org/sonar/plugins/checkstyle/metadata/CheckstyleMetadata.java#L223-L227
it might resolve issue

**Comment by muhlba91** [comment]
@romani thx! 👍 

@gaurabdg removing the line @romani mentioned lowers the coverage of this file to 0.80. Please check or advice.

**Comment by gaurabdg** [comment]
@muhlba91 I think once you merge I will look into it and submit a PR. Also removing 2 extra if conditions 
https://github.com/checkstyle/sonar-checkstyle/blob/c53befb21b10a2354afb9006092f51375c6a1162/src/main/java/org/sonar/plugins/checkstyle/metadata/CheckstyleMetadata.java#L108 will increase the coverage since `metadata-gen` master has been updated to exclude these yet-to-release Check metadata

**Comment by romani** [comment]
[Travis](https://travis-ci.org/github/checkstyle/sonar-checkstyle/jobs/718375574#L613) is not happy with
```
[INFO] --- jacoco-maven-plugin:0.8.5:check (default-check) @ checkstyle-sonar-plugin ---
[INFO] Loading execution data file /home/travis/build/checkstyle/sonar-checkstyle/target/jacoco.exec
[INFO] Analyzed bundle 'checkstyle-sonar-plugin' with 17 classes
[WARNING] Rule violated for class org.sonar.plugins.checkstyle.metadata.CheckstyleMetadata: branches covered ratio is 0.80, but expected minimum is 0.84
```

I think it is ok to make some regression in coverage to make 8.35 release.

**Comment by muhlba91** [comment]
@romani @gaurabdg i will merge but since 4.34 is a pending release as SQ i will not draft the release until 4.34 is through to keep a clean history and upgrade path for people.
hence, @gaurabdg if you find time, please check out if we can increase the coverage, otherwise we will take this regression into the release once https://github.com/SonarSource/sonar-update-center-properties/pull/144 is through.

**Comment by gaurabdg** [comment]
https://github.com/checkstyle/sonar-checkstyle/pull/310 increases branch coverage to 0.82

**Pull request merged**
