### PR TITLE
Issue #502: update to LTS 9.9; cleanup deprecations

### LINKED ISSUE #194: SonarQube 7.6 deprecated org.sonar.api.batch.ScannerSide
In SQ 7.6 `org.sonar.api.batch.ScannerSide` got deprecated and replaced by `org.sonar.api.ScannerSide`. (see https://docs.sonarqube.org/display/DEV/API+Changes)
However, injections of both annotations differ, for example does the new annotation not inject a `JavaResourceLocator` anymore and, therefore, have to refactor the need of it on the scanner side to be compatible with new APIs once the deprecated annotation is removed.

### LINKED ISSUE #220: RulePriority deprecated
As per Sonar `RulePriority` is deprecated: https://github.com/SonarSource/sonarqube/blob/master/sonar-plugin-api/src/main/java/org/sonar/api/rules/RulePriority.java#L30

However, SonarQube itself still uses `RulePriority` as a return value, e.g. in their `ActiveRules`: https://github.com/SonarSource/sonarqube/blob/master/sonar-plugin-api/src/main/java/org/sonar/api/rules/ActiveRule.java#L120.

Hence, once SonarQube removes their usage we can remove the deprecated accesses to `RulePriority` as well.

### LINKED ISSUE #502: Upgrade to 9.9 LTS
SQ LTS is at `9.9`. We still rely on the `8.9` LTS libraries.

1. Update libraries to `9.9` LTS.
2. Cleanup deprecations. (#220, #194 will be included here.)

### PR DESCRIPTION
**Pull request by muhlba91**
fixes #502 
fixes #220 
fixes #194 

Also, remove the deprecated and to be removed `ProfileImporter` and `ProfileExporter`.

Screenshots of the working SQ:
Screenshot 2024-03-01 at 1 01 56 PM
Screenshot 2024-03-01 at 1 01 35 PM

### CODE REVIEW

**Comment by muhlba91** [comment]
@romani the main project deprecated `AutomaticBean` a while ago with the reference one should use `AbstractAutomaticBean`.

unfortunately, by doing so, i now receive a CS error:
```
[ERROR] [checkstyle] [ERROR] /Users/daniel/Projects/checkstyle/sonar-checkstyle-muhlba91/src/main/java/org/sonar/plugins/checkstyle/CheckstyleExecutor.java:41:1: Disallowed import - com.puppycrawl.tools.checkstyle.AbstractAutomaticBean. [ImportControlMain]
```

could you please advise here?

**Comment by romani** [comment]
please add this class to https://github.com/checkstyle/sonar-checkstyle/blob/8462c9e11258cacbf66990d6b512b8386bfbc1a2/config/import-control.xml#L21-L22
and disallow AutomaticBean migration is completed.

**Comment by muhlba91** [comment]
@romani could you please have a look? 😃 

https://app.circleci.com/pipelines/github/checkstyle/sonar-checkstyle/878/workflows/9dfe6b2a-d89d-4cd9-b03b-7d7e95436488/jobs/1035 fails because the SQ java plugin is not compatible with java 11 anymore. i have updated the circleci job to use java 17 but this will only be applied once it's in master. (see change https://github.com/checkstyle/sonar-checkstyle/pull/503/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47)

https://app.circleci.com/pipelines/github/checkstyle/sonar-checkstyle/878/workflows/996f2d0a-8317-4ffe-9d15-027ecedb0db9/jobs/1037 fails but i don't know the reason, tbh. do you have any ideas here?

**Comment by romani** [comment]
Strange, stable failure.
Restart ci on master is passing https://app.circleci.com/pipelines/github/checkstyle/sonar-checkstyle/860/workflows/cb6568c7-6dff-48ab-8f2e-9604d26c7f8a/jobs/1040

Something is this update

**Comment by romani** [comment]
Problem is at this step
https://github.com/checkstyle/sonar-checkstyle/blob/f69a052208febb01d567f932731967986f6eb667/.circleci/config.yml#L26

It might not compatible with docker image for jdk 17, try to remove it or check with git blame why it was added

**Comment by muhlba91** [comment]
awesome, thanks! 😃 circleci jobs are running through now and i migrated one of them to github actions as well.

**Review by romani — APPROVED** [review]
Ok to merge

**Pull request merged**
