### PR TITLE
Issue #229: fix TC errors

### LINKED ISSUE #229: Teamcity is failed in master
https://teamcity.jetbrains.com/viewLog.html?buildId=2373462&tab=Inspection&buildTypeId=Checkstyle_SonarCheckstyleIdeaInspectionsMaster

@muhlba91 , please help to resolve.
not sure how this passed PR.

### PR DESCRIPTION
**Pull request by muhlba91**
fixes #229

### CODE REVIEW

**Comment by romani** [comment]
Ok to merge, if CI pass

**Comment by romani** [comment]
Is there any ideas how it leaked/appears to master ?

**Comment by muhlba91** [comment]
Could it be that there was an update within the checks performed by TC during my last commit and us merging the PR into master?
Hence, the "old" checks ran through without raising an issue and the PR was green but after merging master ran with the new set and raised this issue. Other than that I don't have an explanation for TC not finding this issue as in previous PRs from my side it always worked when there was an issue.

**Comment by romani** [comment]
TC was recently upgraded, caused bunch of problems that ihad to resolve asap in main project to unblock merge process. We did not change code in PR, so TC execution was old.

Ok, happens.

**Pull request merged**
