### PR TITLE
#282 set compatibility to 1.8

### PR DESCRIPTION
**Pull request by BerndFarkaDyna**
#282

## just a test to try if it is possible to set target of the bytecode to 1.8 and keep everything on java 11

### CODE REVIEW

**Comment by muhlba91** [comment]
looks good so far. :+1:

please also try changing the CI to use jdk 8 (except for the travis integration test one).

**Comment by BerndFarkaDyna** [comment]
> looks good so far. 👍
> please also try changing the CI to use jdk 8 (except for the travis integration test one).

sure, but do not test the corner case we are failing then..

since if i change the CI to jdk8 we build with 8 and test with 8 which works…
but I'll give it a try

**Comment by muhlba91** [comment]
sure :)
my reasoning is rather to see whether we can run unit tests with jdk 8 and only use jdk 11 for integration testing or if we then fail due to jdk specifics.

either way, from my point of view, as long as @romani doesn‘t see a blocker, we can build and test solely with jdk 11 as well but keep compatibility at jdk 8.

**Comment by romani** [comment]
> we can build and test solely with jdk 11 as well but keep compatibility at jdk 8.

I am ok, we will unlikely to use jdk11 specfic features in recent future.

**Comment by BerndFarkaDyna** [comment]
unfortunally the test code is seems to use an API which is only available on JDK11..

but anyway; i try to give it a fix

**Comment by muhlba91** [comment]
> I am ok, we will unlikely to use jdk11 specfic features in recent future.

> but anyway; i try to give it a fix

awesome, thanks a lot! :)

btw, as long as i didn‘t mix anything up, this commit contains all fixes for jdk 11: https://github.com/checkstyle/sonar-checkstyle/commit/3195b481378157ed59e7eda912e69e08035a41ed

**Comment by BerndFarkaDyna** [comment]
@muhlba91 , @romani : I made the unit tests compile/work against java8; and squashed my changes, please have a look on my PR and provide some feedback, it would be really great if this could get into master and be released soon..

THX 
Bernd

**Comment by romani** [comment]
@BerndFarkaDyna ,

please update commit message to be `Issue #282: ...... ` it is good to have commit clearly reference to issue. Issue reference PR, ... so even in few years we will easily review whole context of WHY update was done in such way.

@muhlba91 , please reheck on your local, it is critical that you continue to do executions/releases on your local.

**Comment by BerndFarkaDyna** [comment]
@romani  / @muhlba91 : changed the comment.. so everything should be ready for a merge

**Comment by romani** [comment]
@muhlba91 , in core project there is UT that do validation of commit message to follow required format.
you can copy it plugin, this will let you do release without manual modification of release notes.

**Pull request merged**
