### PR TITLE
Issue #28: added validation tokens for all modules

### PR DESCRIPTION
**Pull request by rnveach**
Issue #28

We only validate tokens. We can't validate all properties, like in main checkstyle repo.

This should fix the direct issue in #75 with the parameter type field.

### CODE REVIEW

**Comment by romani** [comment]
@rnveach , please update PR and UT.

1) We need to fallback to STRING only if type become above 512 symbols.
2) We need to keep strict type as much as possible.
3)  please move "<defaultValue></defaultValue>" change to separate  commit at this PR.

**Comment by romani** [comment]
I need to retest type change one more time, please hold on changes

**Comment by romani** [comment]
I retested as:
use sonar with 3.5.1 plugin , do violation at " is not followed by whitespace"
upgrage to 3.6-SNAPSHOT , resolve existing violation
cause violation again.

no problems is detected, so Sonar manage type changes correctly.

@rnveach , please proceed with requested changes.

**Comment by rnveach** [comment]
> please move "" change to separate commit at this PR.

Text should be `"<defaultValue></defaultValue>"` and not empty strings.

**Comment by rnveach** [comment]
@romani tokens for WhitespaceAround  is not 512 characters or greater.
It is only 510 characters. So the test doesn't want it to change to `STRING`.

Can you confirm the full value being inserted into the database?
Looking closer at the #75, it is adding more to the value.
> `'SINGLE_SELECT_LIST,multiple=true,values=""`...

**Comment by romani** [comment]
from #75 .

yes, string value in xml was only 510 characters, in exception there was reference to actual length of string on moment of insert `"ASSIGN,ARRAY_INIT,BAND,BAND_ASSIGN,BOR,BOR_ASSIGN,BSR,BSR_ASSIGN,BXOR,BXOR_ASSIGN,COLO... (549)"`.
No idea what Sonar add at the end of our content.....

**Comment by rnveach** [comment]
@romani Done.

**Comment by romani** [comment]
please rebase to test sonar run in CI on your changes

**Comment by rnveach** [comment]
@romani Done.

**Comment by romani** [comment]
@rnveach , did you test affected modules ? just simple changes of config and make sure Check able to report violation.
I do not want to receive surprise int he day of release.

For now we do not have well designed testing environment to trust automatic testing.
Wercker testing is just testing that Sonar is starting with plugin, it does not test any Checkstyle Checks for now.

**Comment by rnveach** [comment]
> did you test affected modules ? 

If you mean in sonar, I have been unable to get it working in my VM.
I was trying last night and Ubuntu 12.04 had too old a version of MySQL. Ubuntu 16 looked like it was working better, but the web page was still not responding for me and I haven't determined the issue.

**Comment by romani** [comment]
@rnveach , why not to use docker approach ?
Having permanent Sonar on systems is big deal. Did you considered postgres as DB ?

**Comment by rnveach** [comment]
I literally just googled how to install, and instructions were with MySQL and downloading directly from the website.

**Comment by romani** [comment]
fun to continue .... there 44 extra symbols in that column.

from Postgres DB of sonar:
```
select r.plugin_config_key, rp.* from rules_parameters rp 
join rules r on r.id = rp.rule_id
where rp.name ='tokens' and rp.param_type!='STRING'
and r.plugin_config_key='Checker/TreeWalker/IllegalType'
;
-- Output:
-- "Checker/TreeWalker/IllegalType";34;440;"tokens";"SINGLE_SELECT_LIST,multiple=true,values="PARAMETER_DEF,VARIABLE_DEF,METHOD_DEF,"";"VARIABLE_DEF,PARAMETER_DEF,METHOD_DEF";"tokens to check"
13:44:02.178";"";"";"";"";;40;"";"CONSTANT_ISSUE";"";"";"";"2min";"";"";"";f;"MARKDOWN"
```

**Comment by romani** [comment]
release time is at this weekends.

@rnveach , do you need help with testing.

**Comment by romani** [comment]
@rnveach , lets finish this PR ? before we become overbusy in main project.

**Comment by rnveach** [comment]
ok, I'll work on testing it

**Comment by rnveach** [comment]
@romani I tested random checks on this version. I didn't find any problems and all were working fine.

Playing with `JavadocStyleCheck` https://github.com/checkstyle/sonar-checkstyle/pull/77/files#diff-7e847188273a49bacd3f0bad7feffc1aL860 , which has some drastic token changes.
When downgrading to old version existing templates remained. I was able to run the existing rules with no issue with `mvn sonar:sonar`.

But there seemed to be no validation on editing the template. I could add any token I wanted even invalid ones like `a`. I could even add invalid values for `true`/`false`.
`mvn sonar:sonar` failed with the following when trying to run with them:
````
[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar (default-cli) on project checkstyle-sonar-plugin-parent: Can not execute Checkstyle: cannot initialize module TreeWalker - illegal value 'a' for property 'checkFirstSentence' of module JavadocStyle: Can't convert value 'a' to type class java.lang.Boolean -> [Help 1]
````
I tested this with a brand new template, and it happens there too. So it is not related my changes. It happens on editing any existing template.
I will make a new issue for it. Weird it doesn't use same validation as creating a template.

**Comment by romani** [comment]
thanks a lot for fix.
At least we did big step forward in correctness of configuration.
Users will let us know if smth is missed.

**Pull request merged**
