### PR TITLE
Upgragde to Checkstyle 7.0

### PR DESCRIPTION
**Pull request by marschall**
Upgrades the checkstyle version from 6.12.1 to 7.0.

### CODE REVIEW

**Comment by tsjensen** [comment]
Don't you need to update the [rules.xml](https://github.com/checkstyle/sonar-checkstyle/blob/master/sonar-checkstyle-plugin/src/main/resources/org/sonar/plugins/checkstyle/rules.xml) also?

**Comment by marschall** [comment]
You're correct. I will do this.

**Comment by romani** [comment]
It would be better to make few middle versions for version between 6.12 - 6.19, to let use that versions for clients.
it is very beneficial to use the same version of CS in IDE  and build process and in Sonar.

**Comment by tsjensen** [comment]
Well we should be grateful for any version! It is a lot of work to update everything to a new version. If he does it for 7.0, that's fantastic.
In the long run, we should think of ways to avoid this chore.

**Comment by romani** [comment]
I am suggesting gradual update(for each release) of metadata that will be beneficial for all.
Gradual to make it simple to update, final update for metadata will be the same. The simpler update the faster it could be done.

**Comment by romani** [comment]
>In the long run, we should think of ways to avoid this chore.

Yes, such problem have all plugins, we started discussion about this with author of eclipse-cs in our maillist, but we do not have that much members in team to make it happen. Everyone is welcome to contribute.

**Comment by marschall** [comment]
I'll do a new PR for 7.1

**Pull request closed without merging**
