### PR TITLE
Issue #331: fix rule template determination logic

### PR DESCRIPTION
**Pull request by gaurabdg**
#331

Screenshot 2020-09-15 at 3 44 50 AM

### CODE REVIEW

**Comment by romani** [comment]
Please list all non template rules in comment. I will double-check them.

**Comment by romani** [comment]
"minor" is used only for non functional changes. As you fix very big issue, it is better to create issue on it and quickly describe it. Commit should have reference to issue to show whole history of changes

**Comment by romani** [comment]
```
07:55 $ cat ~/java/temp/sonar-rules.txt 
Abbreviation As Word In Name Rule Template
Abstract Class Name Rule Template
Annotation Location Rule Template
Annotation On Same Line Rule Template
Annotation Use Style Rule Template
Anon Inner Length Rule Template
Array Trailing Comma Rule Template
Array Type Style Rule Template
Atclause Order Rule Template
Avoid Double Brace Initialization
Avoid Escaped Unicode Characters Rule Template
Avoid Inline Conditionals
Avoid Nested Blocks Rule Template
Avoid No Argument Super Constructor Call
Avoid Star Import Rule Template
Avoid Static Import Rule Template
Before Execution Exclusion File Filter Rule Template
Boolean Expression Complexity Rule Template
Catch Parameter Name Rule Template
Class Data Abstraction Coupling Rule Template
Class Fan Out Complexity Rule Template
Class Member Implied Modifier Rule Template
Class Type Parameter Name Rule Template
Comments Indentation Rule Template
Constant Name Rule Template
Covariant Equals
Custom Import Order Rule Template
Cyclomatic Complexity Rule Template
Declaration Order Rule Template
Default Comes Last Rule Template
Descendant Token Rule Template
Design For Extension Rule Template
Empty Block Rule Template
Empty Catch Block Rule Template
Empty For Initializer Pad Rule Template
Empty For Iterator Pad Rule Template
Empty Line Separator Rule Template
Empty Statement
Equals Avoid Null Rule Template
Equals Hash Code
Executable Statement Count Rule Template
Explicit Initialization Rule Template
Fall Through Rule Template
File Length Rule Template
File Tab Character Rule Template
Final Class
Final Local Variable Rule Template
Final Parameters Rule Template
Generic Whitespace
Header Rule Template
Hidden Field Rule Template
Hide Utility Class Constructor
Illegal Catch Rule Template
Illegal Identifier Name Rule Template
Illegal Import Rule Template
Illegal Instantiation Rule Template
Illegal Throws Rule Template
Illegal Token Rule Template
Illegal Token Text Rule Template
Illegal Type Rule Template
Import Control Rule Template
Import Order Rule Template
Indentation Rule Template
Inner Assignment
Inner Type Last
Interface Is Type Rule Template
Interface Member Implied Modifier Rule Template
Interface Type Parameter Name Rule Template
Invalid Javadoc Position
Java N C S S Rule Template
Javadoc Block Tag Location Rule Template
Javadoc Content Location Rule Template
Javadoc Method Rule Template
Javadoc Missing Whitespace After Asterisk Rule Template
Javadoc Package Rule Template
Javadoc Paragraph Rule Template
Javadoc Style Rule Template
Javadoc Tag Continuation Indentation Rule Template
Javadoc Type Rule Template
Javadoc Variable Rule Template
Lambda Parameter Name Rule Template
Left Curly Rule Template
Line Length Rule Template
Local Final Variable Name Rule Template
Local Variable Name Rule Template
Magic Number Rule Template
Member Name Rule Template
Method Count Rule Template
Method Length Rule Template
Method Name Rule Template
Method Param Pad Rule Template
Method Type Parameter Name Rule Template
Missing Ctor
Missing Deprecated Rule Template
Missing Javadoc Method Rule Template
Missing Javadoc Package
Missing Javadoc Type Rule Template
Missing Override Rule Template
Missing Switch Default
Modified Control Variable Rule Template
Modifier Order
Multiple String Literals Rule Template
Multiple Variable Declarations
Mutable Exception Rule Template
N Path Complexity Rule Template
Need Braces Rule Template
Nested For Depth Rule Template
Nested If Depth Rule Template
Nested Try Depth Rule Template
Newline At End Of File Rule Template
No Array Trailing Comma
No Clone
No Code In File
No Enum Trailing Comma
No Finalizer
No Line Wrap Rule Template
No Whitespace After Rule Template
No Whitespace Before Rule Template
Non Empty Atclause Description Rule Template
One Statement Per Line Rule Template
One Top Level Class
Operator Wrap Rule Template
Ordered Properties Rule Template
Outer Type Filename
Outer Type Number Rule Template
Overload Methods Declaration Order
Package Annotation
Package Declaration Rule Template
Package Name Rule Template
Parameter Assignment
Parameter Name Rule Template
Parameter Number Rule Template
Paren Pad Rule Template
Pattern Variable Name Rule Template
Record Component Number Rule Template
Record Type Parameter Name Rule Template
recordCompNum
Redundant Import
Redundant Modifier Rule Template
Regexp Rule Template
Regexp Header Rule Template
Regexp Multiline Rule Template
Regexp On Filename Rule Template
Regexp Singleline Rule Template
Regexp Singleline Java Rule Template
Require Empty Line Before Block Tag Group Rule Template
Require This Rule Template
Return Count Rule Template
Right Curly Rule Template
Separator Wrap Rule Template
Severity Match Filter Rule Template
Simplify Boolean Expression
Simplify Boolean Return
Single Line Javadoc Rule Template
Single Space Separator Rule Template
Static Variable Name Rule Template
String Literal Equality
Summary Javadoc Rule Template
Super Clone
Super Finalize
Suppress Warnings Rule Template
Suppress Warnings Filter
Suppress Warnings Holder Rule Template
Suppress With Nearby Comment Filter Rule Template
Suppress With Plain Text Comment Filter Rule Template
Suppression Comment Filter Rule Template
Suppression Filter Rule Template
Suppression Single Filter Rule Template
Suppression Xpath Filter Rule Template
Suppression Xpath Single Filter Rule Template
Throws Count Rule Template
Todo Comment Rule Template
Trailing Comment Rule Template
Translation Rule Template
Type Name Rule Template
Typecast Paren Pad Rule Template
Uncommented Main Rule Template
Unique Properties Rule Template
Unnecessary Parentheses Rule Template
Unnecessary Semicolon After Outer Type Declaration Rule Template
Unnecessary Semicolon After Type Member Declaration Rule Template
Unnecessary Semicolon In Enumeration
Unnecessary Semicolon In Try With Resources Rule Template
Unused Imports Rule Template
Upper Ell
Variable Declaration Usage Distance Rule Template
Visibility Modifier Rule Template
Whitespace After Rule Template
Whitespace Around Rule Template
Write Tag Rule Template
```

```
✔ ~/java/github/checkstyle/sonar-checkstyle [gaurabdg/template-rule-fix L|✔] 
07:56 $ grep -v "Rule Temp" ~/java/temp/sonar-rules.txt 
Avoid Double Brace Initialization
Avoid Inline Conditionals
Avoid No Argument Super Constructor Call
Covariant Equals
Empty Statement
Equals Hash Code
Final Class
Generic Whitespace
Hide Utility Class Constructor
Inner Assignment
Inner Type Last
Invalid Javadoc Position
Missing Ctor
Missing Javadoc Package
Missing Switch Default
Modifier Order
Multiple Variable Declarations
No Array Trailing Comma
No Clone
No Code In File
No Enum Trailing Comma
No Finalizer
One Top Level Class
Outer Type Filename
Overload Methods Declaration Order
Package Annotation
Parameter Assignment
recordCompNum
Redundant Import
Simplify Boolean Expression
Simplify Boolean Return
String Literal Equality
Super Clone
Super Finalize
Suppress Warnings Filter
Unnecessary Semicolon In Enumeration
Upper Ell
```

**Review by muhlba91 — APPROVED** [review]
@romani please approve if the results looks good.
i'll test again and draft a release after this is approved and merged.

**Comment by romani** [comment]
[AvoidDoubleBraceInitialization](https://checkstyle.org/config_coding.html#AvoidDoubleBraceInitialization)
[AvoidInlineConditionals](https://checkstyle.org/config_coding.html#AvoidInlineConditionals)
[AvoidNoArgumentSuperConstructorCall](https://checkstyle.org/config_coding.html#AvoidNoArgumentSuperConstructorCall)
[CovariantEquals](https://checkstyle.org/config_coding.html#CovariantEquals)
[EmptyStatement](https://checkstyle.org/config_coding.html#EmptyStatement)
[EqualsHashCode](https://checkstyle.org/config_coding.html#EqualsHashCode)
[FinalClass](https://checkstyle.org/config_design.html#FinalClass)
[GenericWhitespace](https://checkstyle.org/config_whitespace.html#GenericWhitespace)
[HideUtilityClassConstructor](https://checkstyle.org/config_design.html#HideUtilityClassConstructor)
[InnerAssignment](https://checkstyle.org/config_coding.html#InnerAssignment)
[InnerTypeLast](https://checkstyle.org/config_design.html#InnerTypeLast)
[InvalidJavadocPosition](https://checkstyle.org/config_javadoc.html#InvalidJavadocPosition)
[MissingCtor](https://checkstyle.org/config_coding.html#MissingCtor)
MissingJavadocPackage
MissingSwitchDefault
ModifierOrder
MultipleVariableDeclarations
NoArrayTrailingComma
NoClone
NoCodeInFile
NoEnumTrailingComma
NoFinalizer
OneTopLevelClass
OuterTypeFilename
OverloadMethodsDeclarationOrder
PackageAnnotation
ParameterAssignment
recordCompNum
RedundantImport
SimplifyBooleanExpression
SimplifyBooleanReturn
StringLiteralEquality
SuperClone
SuperFinalize
SuppressWarningsFilter
UnnecessarySemicolonInEnumeration
UpperEll

**Comment by romani** [comment]
@muhlba91 , 
http://localhost:9000/coding_rules?open=checkstyle%3Acom.puppycrawl.tools.checkstyle.filters.SuppressionSingleFilter&q=SuppressionSingleFilter
image

I do support filer to be configured as Rules ? 

I thought that user have to do this
at http://localhost:9000/admin/settings?category=java
image

**Comment by muhlba91** [comment]
yes, filters should be specified in the settings. however, i don‘t remember/know the exact reason for this but i believe it had something to do with generating the correct CS xml for the analysis and what is/was supported - at least when this pattern got introduced.

did we get all available filters as rules now due to metadata?
tbh, if it works without causing problems to be able to specify filters as rules, it might create a nice user experience to have everything in one place and easily configurable (without having to write those xml rules) and being able to see everything that‘s going on in the same place.

what i‘d be more concerned about this new pattern is that a config provides the ability to be specified on a project level - hence, having filters applied only for certain projects and not globally in the SQ quality profile.

in fact, out of a user‘s perspective, does it make sense to actually keep both?
1) in a SQ rule it‘s easy to configure and visible, and 2) can be applied on a project level for certain use cases through a xml config excerpt.
we might want to adapt the config description to state the purpose correctly but it provides great flexibility (assuming the filter as rule actually gets processes by CS analysis correctly).

**Comment by muhlba91** [comment]
for the filter i receive:
`Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module SuppressWarningsFilter - Property 'severity' does not exist, please check the documentation`. this happens to all filters.
@gaurabdg please filter out filters when creating rules.

**Comment by romani** [comment]
@muhlba91 , please play/test with other new Checks from 8.36 to make sure that they works and all we need to do release and finish metadata is remove filters from list of Rules.
@gaurabdg , please finish this, looks like we are in last step before completion.

**Comment by gaurabdg** [comment]
@romani Done

**Comment by romani** [comment]
works for me 
image

**Review by romani — APPROVED** [review]

**Pull request merged**
