### PR TITLE
Issue #160: fix teamcity violations

### PR DESCRIPTION
**Pull request by rnveach**
#160 and the start of #161

### CODE REVIEW

**Comment by rnveach** [comment]
PMD violation:

````
[INFO] --- maven-pmd-plugin:3.7:check (default) @ checkstyle-sonar-plugin ---
[INFO] PMD Failure: org.sonar.plugins.checkstyle.CheckstyleExecutor:146 Rule:OptimizableToArrayCall Priority:3 This call to Collection.toArray() may be optimizable.
````

**Comment by rnveach** [comment]
teamcity is still failing with:
> Zero-length array allocation (1)
> 146: createClassloader() Allocation of zero length array

**Comment by rnveach** [comment]
Everything is passing. I will fix commits.

**Comment by romani** [comment]
@rnveach , please review issues if they are ok to be closed.

**Pull request merged**
