### PR TITLE
Upgragde to Checkstyle 7.1

### PR DESCRIPTION
**Pull request by marschall**
Upgrades the checkstyle version from 6.12.1 to 7.1.

 - upgrade the dependencies
 - upgrade the rules.xml

### CODE REVIEW

**Comment by tsjensen** [comment]
Thank you! This will be very helpful. :+1:

**Comment by romani** [comment]
thanks a lot.

Your commit was redone with minor changes.
version will be 3.1 to correspond to 7.1.
2.4 versions of plugin  will be a allocated for 6.XX releases of checkstyle.

**Comment by romani** [comment]
@marschall , please confirm that binaries for HEAD master works for your version of Sonar.
As I have more time, I will do official release.

**Comment by marschall** [comment]
@romani the version of the sub module POMs needs to be updated to 3.1-SNAPSHOT as well and one of the tests fails locally because of a missing translation. I'll do a pull request that fixes this. Do you know if I also have to update `checkstyle-model.xml`?

**Pull request closed without merging**
