### PR TITLE
Issue #145: Templatise the Separator Wrap rule 

### PR DESCRIPTION
**Pull request by jgchristian**
Issue #145 change to support multiple instances. Not sure what would happen if people already have this rule configured in a singular manner.

### CODE REVIEW

**Comment by jgchristian** [comment]
Tested how my change handles the upgrade.  Seems fine.  The old singular rule continues to be applied, even though a warning is displayed

Steps to verify
- With plugin 4.8 installed via Marketplace, activate Separator Wrap rule on a profile.
- Stop Sonar
- Deploy version of plugin with the change to Sonar
- Start Sonar
- Navigate to the rule (which is now tagged as a Template)
- Warning displayed " This rule template was activated on the following profiles in previous versions of SonarQube. It is not possible anymore to do so. Instead, please create a custom rule. "
- Activate a scan on a project with the profile enabled
- Inspect the target/sonar/checkstyle.xml file downloaded from Sonar
-- It continues to include the old singular rule <module name="SeparatorWrap"><property name="severity" value="info"/><property name="tokens" value="DOT,COMMA"/><property name="option" value="eol"/></module>
- Back in Sonar, create a custom rule from the new template and assign to a profile
-- Separator Wrap page shows it as both a rule (with warning mentioned above) in the Quality Profiles sections  AND a Custom Rule
- Activate a scan on a project with the profile enabled
- Inspect the target/sonar/checkstyle.xml file downloaded from Sonar
-- see both rules active in the generated file

**Comment by romani** [comment]
Thanks a lot for detailed testing steps it awesome.

Please do one update for git commit message and add reference to issue as prefix "Issue #145: ..."
We use this for release notes generation, release will be at this weekend.

Please move side effect description to issue, users will find it base on release notes quicker than in PR, it will help them to understand why it happens.

**Comment by jgchristian** [comment]
@romani added commit as suggested

**Comment by romani** [comment]
thanks a lot, but please amend existing commit, there should be only one commit.
thanks in advance.

**Comment by agsmorodin** [comment]
Can we expect this fix to be a part of a release soon?

**Comment by romani** [comment]
Sorry that we have delay in releases, you can always refer to dates of milestones at GitHub, I keep them actual always.

We had a delay with release of main library ( we are blocked by sourceforge issue, broken ssh access), plugin is attached to main library for now. 

Expect release at the last weekend of March.
If needed it sooner, package plugin yourself and substitute jar in sonar plugin folder.

**Pull request merged**
