### PR TITLE
config: upgrade sevntu to 1.44.1

### PR DESCRIPTION
**Pull request by rnveach**

### CODE REVIEW

**Comment by romani** [comment]
Ok to merge if CI is green

**Comment by rnveach** [comment]
````
Error: style] [ERROR] /home/runner/work/sonar-checkstyle/sonar-checkstyle/src/main/java/org/sonar/plugins/checkstyle/CheckstyleExecutor.java:64:7: @noinspection Javadoc tags should be accompanied by a                      @noinspectionreason tag, explaining why we suppressed inspection. [MatchXpath]
Error: style] [ERROR] /home/runner/work/sonar-checkstyle/sonar-checkstyle/src/main/java/org/sonar/plugins/checkstyle/metadata/CheckstyleMetadata.java:243:21: Name 'x' must match pattern '^(id)|([a-z][a-z0-9][a-zA-Z0-9]+)$'. [LocalVariableName]
Error: style] [ERROR] /home/runner/work/sonar-checkstyle/sonar-checkstyle/src/main/java/org/sonar/plugins/checkstyle/metadata/CheckstyleMetadata.java:348:22: Name 'i' must match pattern '^(id)|([a-z][a-z0-9][a-zA-Z0-9]+)$'. [LocalVariableName]
Error: style] [ERROR] /home/runner/work/sonar-checkstyle/sonar-checkstyle/src/test/java/org/sonar/plugins/checkstyle/CheckstyleAuditListenerTest.java:79:7: @noinspection Javadoc tags should be accompanied by a                      @noinspectionreason tag, explaining why we suppressed inspection. [MatchXpath]
Error: style] [ERROR] /home/runner/work/sonar-checkstyle/sonar-checkstyle/src/test/java/org/sonar/plugins/checkstyle/CheckstyleExecutorTest.java:106:7: @noinspection Javadoc tags should be accompanied by a                      @noinspectionreason tag, explaining why we suppressed inspection. [MatchXpath]
````

**Review by romani — APPROVED** [review]
ok to merge

**Comment by romani** [comment]
@muhlba91 , fyi, there is not functional changes, just code cleanup

**Pull request merged**
