### PR TITLE
Issue #114: fix javadocTokens values for NonEmptyAtclauseDescriptionCheck

### PR DESCRIPTION
**Pull request by dancing-leaves**
Issue: #114

### CODE REVIEW

**Comment by rnveach** [comment]
test error:
>   ChecksTest.verifyTestConfigurationFiles:92->validateSonarRules:106->validateSonarRules:152->validateSonarRuleProperties:221 com.puppycrawl.tools.checkstyle.checks.javadoc.NonEmptyAtclauseDescriptionCheck has the parameter 'javadocTokens' in sonar rules with the incorrect type expected:<s[[VARIABLE_DEF,INSTANCE_INIT,ARRAY_DECLARATOR,CTOR_DEF]]> but was:<s[[PARAM_LITERAL,RETURN_LITERAL,THROWS_LITERAL,DEPRECATED_LITERAL]]>

http://checkstyle.sourceforge.net/config_javadoc.html#NonEmptyAtclauseDescription
> subset of javadoc tokens PARAM_LITERAL, RETURN_LITERAL, THROWS_LITERAL, DEPRECATED_LITERAL. 

It looks like something is wrong with the test to validate the XML file. I will look into this.

**Comment by romani** [comment]
@dancing-leaves ,  we have problems in CIs due to unrelated to your changes problem:
```
ChecksTest.verifyTestConfigurationFiles:92->validateSonarRules:106->validateSonarRules:152->validateSonarRuleProperties:221 com.puppycrawl.tools.checkstyle.checks.javadoc.NonEmptyAtclauseDescriptionCheck has the parameter 'javadocTokens' in sonar rules with the incorrect type expected:<s[[VARIABLE_DEF,INSTANCE_INIT,ARRAY_DECLARATOR,CTOR_DEF]]> but was:<s[[PARAM_LITERAL,RETURN_LITERAL,THROWS_LITERAL,DEPRECATED_LITERAL]]>
```

Can you help us to update this UT ? It is wrong .

@rnveach , FYI.

**Comment by rnveach** [comment]
I see issue.
https://github.com/checkstyle/sonar-checkstyle/blob/3fa8f1e76a84e09b29b1ca2374171a5dfb3afaab/checkstyle-sonar-plugin/src/test/java/org/sonar/plugins/checkstyle/internal/ChecksTest.java#L208-L210
>                     expectedTokenType = "s[" + CheckUtil.getTokenText(
                            ((AbstractJavadocCheck) instance).getAcceptableJavadocTokens(),
((AbstractJavadocCheck) instance).getRequiredJavadocTokens()) + "]";

We are calling `CheckUtil.getTokenText` instead of `CheckUtil.getJavadocTokenText`.
All our javadocs with optional tokens are displaying the wrong text.

**Comment by dancing-leaves** [comment]
Hi. So should I just update pull request with @rnveach's fix?

**Comment by rnveach** [comment]
@dancing-leaves Please do.
Verify all tests pass locally before pushing with `mvn clean verify -B -e -V`.
More checks could be affected by this bug.

**Comment by rnveach** [comment]
@dancing-leaves Thanks for working with us.

**Pull request merged**
