### PR TITLE
[WIP] Issue #412: use Github Actions as CI

### LINKED ISSUE #412: Migrate all jobs from Wercker to Travis or any other CI
Wercker will be shut down on oct 31 2022

we need to stop using it.
Move all to Travis or any other CI, main repo has bunch CI in use.

### PR DESCRIPTION
**Pull request by muhlba91**
fixes #412

### CODE REVIEW

**Comment by muhlba91** [comment]
@romani can you please set the `SONAR_TOKEN` secret in this repo?

**Comment by romani** [comment]
secret was added here https://github.com/organizations/checkstyle/settings/secrets/actions
image


by instructions of https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-an-organization

token is my private account sonar token (I do not see organization secrets) - create at https://sonarcloud.io/account/security/

**Comment by muhlba91** [comment]
@romani thanks! i figured out why it doesn't pick it up and i believe we need to use any other CI tool for SQ validations. GitHub Actions doesn't populate secrets to PRs with a different source repository than this one.

i saw we use CircleCI in the main repo as well - any chances to have CircleCI enabled for this one with that token?

**Comment by romani** [comment]
I setup it now - https://app.circleci.com/pipelines/github/checkstyle/sonar-checkstyle

**Comment by muhlba91** [comment]
unfortunately, they all require the `SONAR_TOKEN` secret and in all actions/pipelines/... repository/organization secrets are not passed to workflows from any fork due to security reasons. i didn't find an option to enable this.

qq: did you set the `SONAR_TOKEN` in CircleCI as well already?
unfortunately, i can't use an own token as i don't have "write" access to the sonarcloud project.

**Comment by romani** [comment]
I didn't put, as there is same security problem.

I do not remember where I setup sonarqube as application in our organization, so it does not require shell hacking.

**Comment by muhlba91** [comment]
how did you solve this in the main repo? i saw you used circleci there, also for PRs; hence, my thought to go with that one.

**Pull request closed without merging**
